### ISSUE TITLE
Error while setting data series by setDataSeries() in PHP version 7.1 and above.

### ISSUE THREAD

**Issue by hybridnighthawk** [zingchart/ZingChart-PHP#7]
The error message is : `A non well formed numeric value encountered`. Error happens in `php_wrapper/zc.php` file line 345:
`$index = (substr($chain[0], $indexStart+1, ($indexEnd-$indexStart)+1))*1;`

**Comment by jfrederich** [comment]
@hybridnighthawk Hi Hybridnighthawk,

The issue is that PHP 7.1 added new warnings when you try to use strings in math. Therefore you are running into the `E_NOTICE` error talked about here: https://wiki.php.net/rfc/invalid_strings_in_arithmetic

We are looking into fixing that line of code in the wrapper to update to PHP 7.1 but for now you can ignore `E_NOTICE` level warnings.

**Comment by hybridnighthawk** [comment]
Solving by parsing the strings into float should solve it, right?
